# Generated by Django 2.1.1 on 2019-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_goods', '0002_auto_20190619_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(upload_to='static/goods'),
        ),
    ]
