# Generated by Django 2.1.1 on 2019-06-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_goods', '0003_auto_20190619_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(upload_to='goods'),
        ),
    ]
