# Generated by Django 2.1.1 on 2019-06-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upassword', models.CharField(max_length=100)),
                ('uemail', models.CharField(max_length=100)),
                ('ushouAddress', models.CharField(default='', max_length=200)),
                ('uaddress', models.CharField(default='', max_length=200)),
                ('upostcode', models.CharField(default='', max_length=6)),
                ('uphone', models.CharField(default='', max_length=11)),
                ('ulevel', models.IntegerField(null=True)),
            ],
        ),
    ]
